# System run tests
name: Sonia-CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-test:
    name: Setup-testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  ci-test:
    needs: setup-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    name: CI-Unit
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run test